switched sizes of config boxes
atomicjolt/lti_starter_app pull request #555
Opened 2023-02-21 22:09 UTC by lautom36

PT story -> https://www.pivotaltracker.com/n/projects/2057131/stories/180200559

2023-02-23 17:50 UTC, mpetrowi approved these changes

2023-02-23 18:07 UTC, mpetrowi requested changes
Actually I think this should be changed.  If an MCQ is created with 0 feedback attempts, it allows infinite attempts per the learnosity docs.  So this would change that behavior.

2023-02-23 18:08 UTC, mpetrowi approved these changes

2023-02-23 18:08 UTC, mpetrowi commented
Approved.  sorry, commenting on the wrong PR

2023-03-29 22:22 UTC, jbasdf approved these changes

2023-03-30 20:17 UTC, closed without merging